2.1/create referee
Referite/Referite-Backend pull request #4
Opened 2023-10-19 08:56 UTC by koonwill

Done please check

2023-10-19 14:56 UTC, Tezigudo commented
LGTM but I will test it first

2023-10-21 04:23 UTC, Tezigudo approved these changes

2023-10-21 04:23 UTC, Tezigudo commented on main.py
> +                            value=f"Bearer {access_token}", httponly=True, expires=2073600)
24 day is too long, 30 min - 1 hr is enough

2023-10-27 02:43 UTC, Tezigudo requested changes
change based on my comment

2023-10-27 02:43 UTC, Tezigudo commented on models.py
> +    pass
remove it

2023-10-27 02:43 UTC, Tezigudo commented on requirements.txt
> +beanie
remove it

2023-10-27 02:43 UTC, Tezigudo commented on router/auth.py
> +SECURE = config("SECURE", default=False, cast=bool)
name is not clear, change it pls

2023-10-27 02:43 UTC, Tezigudo commented on sample.env
> +SECURE = False # Change to True if prod, False if testing.
HTTP_COOKIE_SECURE? or COOKIE_SECURE?

2023-10-27 02:45 UTC, koonwill commented on auth/cookie.py
> +              raise HTTPException(status_code=302, detail="Not authorized", headers = {"WWW-Authenticate": "Bearer", "Location": "https://www.google.com/"} )
Location is redirect to the page
In this case I set it to google if not authorize for testing

2023-10-27 02:51 UTC, koonwill commented on db.py
> +sport_type_connection = mongo_connection['SportType']
for further implementation I have used sport_connection to easily get all of the sport on /api/schedule/sport that was merge before, So we didn't need loop or slicing it

2023-10-27 03:41 UTC, Tezigudo approved these changes
resolve conversation first

2023-10-27 03:41 UTC, Tezigudo commented on db.py
> +sport_type_connection = mongo_connection['SportType']
what about sport_type?

2023-10-27 03:41 UTC, Tezigudo commented on router/auth.py
> +router = APIRouter(prefix='/auth',
wtf where/api

2023-10-27 03:41 UTC, Tezigudo commented on router/auth.py
> +async def login(response: Response, form_data:OAuth2PasswordRequestForm = Depends()):
why it **asyncronous** now? we didnt need `async` and `await` now because we use pymongo

2023-10-27 03:41 UTC, Tezigudo commented on router/auth.py
> +async def get_user(user = Depends(get_current_user)):
this too

2023-10-27 03:41 UTC, Tezigudo commented on router/auth.py
> +async def toast():
this too

2023-10-27 03:41 UTC, Tezigudo commented on auth/cookie.py
> +    async def __call__(self, request: Request) -> Optional[str]:
oh I see it now its ok

2023-10-27 05:16 UTC, merged